altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  093af42c-c64c-436c-a27b-07618df14736:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-09T18:28:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 881f9b7a-8def-40cc-8fb7-6e9dd668b47c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-20T16:46:21+00:00'
            elementCondition: null
            fieldUid: 344ae6ed-1f83-4553-9005-228bc5d8ecbb
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edee0c79-c142-43d4-bdac-e6243bdf8ecb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00f207a0-e86a-4b18-b2c2-8fc60ff76127
        userCondition: null
fs: publicFiles
handle: documents
name: Documents
sortOrder: 2
subpath: documents
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
