altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  0215407d-eb1a-460a-a29e-82eaf32b9a27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-26T13:37:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 61863d13-0c70-4c5c-8d62-0d1da346845f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-09-26T13:37:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 0337dd87-2168-4ee3-bf75-938ee77c0160
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-20T16:10:52+00:00'
            elementCondition: null
            fieldUid: 344ae6ed-1f83-4553-9005-228bc5d8ecbb
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb993a84-da39-496a-87cc-1093165026c8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54f1f323-18a3-44ab-ac30-058d00abe054
        userCondition: null
fs: publicFiles
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
