color: null
fieldLayouts:
  d067d50a-35ad-49e1-a0cc-5d1b8695f10b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-30T14:48:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3e7755cb-5894-4967-9034-ede0d25c4ac8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-30T14:51:45+00:00'
            elementCondition: null
            fieldUid: c468560b-ca97-4c24-9834-78d8107d6369
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f19005f-eac8-44c6-bfbf-73bf1f8fe7aa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: adf94689-af8e-420e-89cd-a8e307cb9b73
        userCondition: null
handle: articlesBlock
hasTitleField: false
icon: newspaper
name: 'Articles Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{articleCategory[0]}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
