color: null
fieldLayouts:
  70574638-c949-4fe2-9d72-b9cec54ac40f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-09T18:44:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'H2 tag'
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc353b6b-fde3-4013-9848-674c13033a93
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-09T18:44:39+00:00'
            elementCondition: null
            fieldUid: 5a313bb8-30df-4d3c-9108-cbc12983eedb # Subhead
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e8275d7-09ea-43de-a6b3-a6e92d129f56
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-09T18:44:39+00:00'
            elementCondition: null
            fieldUid: e7161c3c-cfab-42e8-8af6-a0558d1a7a02 # Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f71e610-33ca-479b-a1cd-0d3db6c37734
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T18:58:05+00:00'
            elementCondition: null
            fieldUid: cc3defbc-0d81-4e42-9b3c-8af6137b5348 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5483b0a5-cffa-4bc3-9cc8-9943fa5d76e0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ccf4aff0-04f0-48d1-82be-838849ced56d
        userCondition: null
handle: copyBlock
hasTitleField: true
icon: book
name: 'Copy Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
