color: null
fieldLayouts:
  bdc71a53-e2a3-4b12-9f3e-f5e6d1834de1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T19:07:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 899efe7b-5429-4b17-ac01-088c4ee6f383
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:11:28+00:00'
            elementCondition: null
            fieldUid: c5945a7c-e66f-42b3-b613-59a81282be36 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7f1dff2-09fd-4f22-9a36-c5b907d7a68c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:11:28+00:00'
            elementCondition: null
            fieldUid: cc3defbc-0d81-4e42-9b3c-8af6137b5348 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2300a8b3-c33e-49ad-998a-31e39438518f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:49:55+00:00'
            elementCondition: null
            fieldUid: bdc174bf-0e25-406a-96cd-af4069320925
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9315b0e-a317-4595-b310-b3622f0f1beb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:11:28+00:00'
            elementCondition: null
            fieldUid: 436f7288-0c3e-40b3-9c45-9aff90c758a8 # Hours
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4fc1f10-08e4-43b7-860f-2523e1ea5145
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 806d32e7-cac6-4c85-8804-6fe280a77010
        userCondition: null
handle: hoursBlock
hasTitleField: true
icon: clock
name: 'Hours Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
