color: null
fieldLayouts:
  26a14d9f-109b-46f9-b451-277bf4b5b1b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-09T18:45:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1ae73957-288c-492e-bcef-ad112214da2d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-09T18:45:02+00:00'
            elementCondition: null
            fieldUid: c5945a7c-e66f-42b3-b613-59a81282be36 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b62f109-7cc6-4f55-82fe-ac6dff9426ed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3d188d8f-ceee-4ce0-b815-a573fef362a2
        userCondition: null
handle: imageBlock
hasTitleField: true
icon: images
name: 'Image Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
