columnSuffix: null
handle: address
instructions: null
name: Address
searchable: true
settings:
  maxAddresses: 2
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
