columnSuffix: null
handle: copy
instructions: null
name: Copy
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: e867fb38-3c9f-4190-81dc-b6cb8d8f9827 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
