columnSuffix: null
handle: service
instructions: null
name: Service
searchable: true
settings:
  createButtonLabel: null
  entryTypes:
    - 43791e05-e2b1-4dc1-a36d-b8f011b1fff8 # Services
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
