fieldLayouts:
  94684194-3f8e-4ef6-985c-460cacf8a985:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-24T15:45:43+00:00'
            elementCondition: null
            fieldUid: 360d6d5a-3e88-44e1-99d9-0dba8cd5a8a9 # Address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8c1273c-5b10-4ab0-ab29-b2b2e64c0138
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-04T19:26:17+00:00'
            elementCondition: null
            fieldUid: cd6f59ae-75ab-4a65-ac22-bc9a12595aef # Phone
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe68d181-7e86-481d-a219-d9e671dcbce4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-04T19:26:17+00:00'
            elementCondition: null
            fieldUid: a947ea7f-e48b-412e-84d0-f993a76cbcb1 # Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b663a79e-4f5f-4ef8-b97e-4950e9470cac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 89d67460-4080-4349-9c12-c798c8a064af
        userCondition: null
handle: contact
name: Contact
sortOrder: 2
