fieldLayouts:
  04b36d62-3f1b-4e21-ac58-d025c6387e31:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-24T15:42:25+00:00'
            elementCondition: null
            fieldUid: 88250a3d-1689-491d-a14b-a2c9aeefcbbd
            handle: socialLinks
            includeInCards: false
            instructions: null
            label: 'Social Links'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 530349f7-d1ec-4801-b062-91b07ad3cc87
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 61f933c5-8ecb-459d-a3f9-0fccde232063
        userCondition: null
handle: socialMedia
name: 'Social Media'
sortOrder: 6
