isPublic: false
name: Private
scope:
  - 'sites.9edae570-63e2-4382-9220-af482b3a8ea0:read' # Outside The Lobby
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.bfa495bb-915e-4041-abab-29c9051a7ae5:read' # Home
  - 'sections.5a7dc087-eef8-45db-970a-1d8049f9d7bc:read' # Admin Guide
  - 'sections.d7a06f05-30db-4e6f-aa07-5cf7f54ed82f:read' # Content Pages
  - 'nestedentryfields.e7161c3c-cfab-42e8-8af6-a0558d1a7a02:read' # Copy
  - 'nestedentryfields.f313549c-4817-4ca5-8e62-bd143320326a:read' # Content Blocks
  - 'nestedentryfields.a1ea9dce-08e7-405b-a77d-ec625d8534d2:read' # CTA Blocks
  - 'nestedentryfields.f22c0733-8ca9-49c3-a2d0-af18ffcb5d63:read' # FAQ
  - 'volumes.ce985485-f319-4eaf-ad85-a67a23083a7b:read' # Images
  - 'volumes.6ddafe28-7e96-4bb7-bf31-25db29ddc352:read' # Documents
  - 'globalsets.e85c9eb1-a196-4658-88ec-5702444c8fe5:read' # Contact
  - 'globalsets.df97141f-2aa8-499e-91c6-9437240f4508:read' # Header
  - 'globalsets.ccaf1af6-6ad2-4458-ab7d-a40e192d9a59:read' # Footer
  - 'globalsets.a729f261-6b41-424c-9461-849b691ee23a:read' # Social Media
  - 'taggroups.c9cffc4a-2bfa-483d-809f-8dbc5bd9b56c:read' # Blog Tags
  - 'navigationNavs.all:read'
  - 'navigationNavs.16ccd7b0-a942-4f02-9d0b-d09a23b37f12:read' # Header
  - 'navigationNavs.63d18cba-28fe-42ee-a761-c302a4b0ea09:read' # Footer
